[tool.poetry]
name = "schedule_state"
version = "0.14.0"
description = ""
authors = ["Aneesh Dalvi <2533133+aneeshd@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.10"
portion = "==2.3.0"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
isort = "^5.10.1"
flake8 = "^6.0.0"
holidays = "^0.19"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
homeassistant = "^2022.9.5"
pytest-homeassistant-custom-component = "^0.12.5"
mypy = "^0.991"
coverage = "^6.4.2"
codespell = "^2.2.1"

[tool.poetry.group.dev.dependencies]
pyupgrade = "^2.38.2"
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core>=1.2.0"]
build-backend = "poetry.core.masonry.api"
