default_config:

automation: !include automations.yaml

logger:
  default: warning
  logs:
    custom_components.schedule_state: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

sun:

binary_sensor:
  - platform: workday
    country: CA
    province: "ON"

sensor schedules: !include_dir_merge_list schedules/

homeassistant:
  packages: !include_dir_named issues

input_boolean:
  manual_mode:
    name: Manual mode
  vacation_mode:
    name: Vacation mode

input_datetime:
  special_event_start:
    "name": "Special Event Start"
    "has_date": false
    "icon": "mdi:calendar-start"
    "has_time": true

input_number:
  special_event_duration:
    "name": "Special Event Duration"
    "min": 0.0
    "max": 1440.0
    "icon": "mdi:timeline-clock"
    "step": 1.0
    "mode": "slider"

input_select:
  special_event:
    "name": "Special Event"
    "icon": "mdi:calendar-star"
    "options":
      - "choring"
      - "pitter-patter"
      - "donny-brook"
