default_config:

automation: !include automations.yaml

logger:
  default: error
  logs:
    custom_components.schedule_state: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

sun:

binary_sensor:
  - platform: workday
    country: CA
    province: "ON"

sensor:
  - platform: schedule_state
    name: Sun tracker
    refresh: "1:00:00"
    events:
      - state: night # try this instead of default_state
      - start_template: "{{ states.sun.sun.attributes.next_dawn }}"
        end_template: "{{ states.sun.sun.attributes.next_rising }}"
        state: twilight
      - start_template: "{{ (states.sun.sun.attributes.next_rising | as_timestamp) - 600 }}" # 10 minutes before sunrise
        end_template: "{{ states.sun.sun.attributes.next_setting }}"
        state: day
      - start_template: "{{ states.sun.sun.attributes.next_setting }}"
        end_template: "{{ states.sun.sun.attributes.next_dusk }}"
        state: twilight

sensor schedules: !include_dir_merge_list schedules/
