default_config:

automation: !include automations.yaml

logger:
  default: warning
  logs:
    custom_components.schedule_state: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

sun:

sensor schedules: !include_dir_merge_list schedules/

homeassistant:
  packages: !include_dir_named issues

input_boolean:
  manual_mode:
    name: Manual mode
  vacation_mode:
    name: Vacation mode
  workday:
    name: Workday
  bedroom_bedside_lamps:
    name: Bedroom bedside lamps (Issue 92)

input_datetime:
  special_event_start:
    "name": "Special Event Start"
    "has_date": false
    "icon": "mdi:calendar-start"
    "has_time": true

input_number:
  special_event_duration:
    "name": "Special Event Duration"
    "min": 0.0
    "max": 1440.0
    "icon": "mdi:timeline-clock"
    "step": 1.0
    "mode": "slider"

input_select:
  special_event:
    "name": "Special Event"
    "icon": "mdi:calendar-star"
    "options":
      - "choring"
      - "pitter-patter"
      - "donny-brook"

binary_sensor:
  platform: template
  sensors:
    workday:
      value_template: "{{ is_state('input_boolean.workday', 'on') }}"
    workday_sensor:
      value_template: "{{ is_state('input_boolean.workday', 'on') }}"

light:
  - platform: template
    lights:
      # for issue 92
      bedroom_bedside_lamps:
        value_template: "{{ is_state('input_boolean.bedroom_bedside_lamps', 'on') }}"
        turn_on:
          action: input_boolean.turn_on
          target:
            entity_id: input_boolean.bedroom_bedside_lamps
          data: {}
        turn_off:
          action: input_boolean.turn_off
          target:
            entity_id: input_boolean.bedroom_bedside_lamps
          data: {}
