name: isort
 
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v3"
        - uses: "actions/setup-python@v4"
          with:
            python-version: "3.x"
        - run: python3 -m pip install isort
        - run: isort -c .
 
