name: isort
 
on:
  pull_request:
  push:

jobs:
  style:
    runs-on: "ubuntu-latest"
    name: Check style formatting
    steps:
        - uses: "actions/checkout@v2"
        - uses: "actions/setup-python@v1"
          with:
            python-version: "3.x"
        - run: python3 -m pip install isort
        - run: isort -c .
 
